"""Add post_id to Buy table

Revision ID: 262d7bd81785
Revises: f6d934275b4a
Create Date: 2024-10-10 01:45:02.714063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262d7bd81785'
down_revision = 'f6d934275b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_buy_post_id_posts'), 'posts', ['post_id'], ['id'])

    with op.batch_alter_table('sell', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_sell_post_id_posts'), 'posts', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sell', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sell_post_id_posts'), type_='foreignkey')
        batch_op.drop_column('post_id')

    with op.batch_alter_table('buy', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_buy_post_id_posts'), type_='foreignkey')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
